### ISSUE TITLE
Is ThriftClient usable in browser?

### ISSUE THREAD

**Issue by abelnation** [creditkarma/thrift-server#86]
Trying to get it working with webpack, but it seems that it depends on too many node-specific deps.  Have you guys had any luck (or even tried) making thrift calls from a browser?

**Comment by kevin-greene-ck** [comment]
No, we haven't tested in the browser and I wouldn't expect it to work. The HTTP client you get from this library relies on a connection object built around the `request` library which uses Node's `http` module.

```
const connection = new HttpConnection(...)
const client = new ThriftClient(connection)
```

One could create there own connection object, extending `ThriftConnection` (https://github.com/creditkarma/thrift-server/blob/master/packages/thrift-server-core/src/main/types.ts#L34), built around something like `fetch` or `XMLHttpRequest` to get the client to work in the browser. Beyond that you would need a global polyfill for Node's `Buffer` object, which there are already a few options there.

I would like at some point to add browser support, but it's not our internal use case so it's hard to put priority on it.

**Comment by kevin-greene-ck** [comment]
Closing in favor of #87
